### ISSUE TITLE
markdown not working

### ISSUE THREAD

**Issue by sra-minshall** [gcalmettes/reveal.js-webpack-kit#11]
Hello Guillaume, 

I like what you've done here! I've been trying to understand why markdown syntax does not work as expected. For example adding a section such as:

```
<section data-markdown>
	<textarea data-template>
		## Page title

		A paragraph with some text and a [link](http://hakim.se).
	</textarea>
</section>
```

Renders a textarea element as if in a form. Have you had any success with using markdown in this setup.

Simon

**Comment by gcalmettes** [comment]
Hi Simon,
Thanks for reporting the issue.
The markdown plugin is not present by default, did you try adding it as described in https://revealjs.com/markdown/#markdown-plugin ?

I’ll check on my hand and troubleshoot if necessary.

Guillaume

**Comment by sra-minshall** [comment]
Thanks, actually it was a pretty simple fix :)

```
diff --git a/src/_scripts/reveal-dependencies.js b/src/_scripts/reveal-dependencies.js
index 93b25ac..59f7ed6 100755
--- a/src/_scripts/reveal-dependencies.js
+++ b/src/_scripts/reveal-dependencies.js
@@ -5,6 +5,9 @@ import 'nodePath/reveal_external/external/external.js'
 // Handy menu
 import 'nodePath/reveal.js-menu/menu.js'
 
+// Enable markdown support
+import 'nodePath/reveal.js/plugin/markdown/marked.js'
+import 'nodePath/reveal.js/plugin/markdown/markdown.js'
 
 // Speaker notes
 import './reveal-plugins/reveal-notes.js'
```

**Comment by gcalmettes** [comment]
Glad it worked out fine !
