### ISSUE TITLE
Easiest way to tell versions in this project

### ISSUE THREAD

**Issue by blachawk** [gcalmettes/reveal.js-webpack-kit#7]
What would be the easiest way to tell what version of Reveal.js is associated to this project?

**Comment by gcalmettes** [comment]
Hi,
You can find all the dependencies in the `package.json` file. Right now it is `reveal.js": "^3.7.0` but you could update to the latest if needed.

**Comment by blachawk** [comment]
when you say update, you mean I can update it from the terminal via npm correct?

**Comment by gcalmettes** [comment]
yes indeed
