### ISSUE TITLE
adding htmlwebpackplugin

### ISSUE THREAD

**Issue by blachawk** [gcalmettes/reveal.js-webpack-kit#8]
Is it possible to associate **htmlwebpackplugin** to this project.  If so, what modifications should I be aware of in order to proceed? My motivation is to create multiple directories, representing their own reveal.js projects.  Now if that option is already built into this project, my bad, I didn't get that far in the reading.

**Comment by gcalmettes** [comment]
yes, this project already use `htmlwebpackplugin` see the webpack.config.js file 
https://github.com/gcalmettes/reveal.js-webpack-kit/blob/b3302d2219b95743feb678a5c96dcb8fa021bf05/webpack.config.js#L3
